# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.SERVICE_ACCOUNT_KEY_BASE64 }}

      - name: Google App Engine (GAE) Deploy
        # You may pin to the exact commit or the version.
        # uses: atRobertoFlores/gae_deploy_action@b1ff9efc841e7415ba3510bf94b23c8fb46197eb
        uses: atRobertoFlores/gae_deploy_action@1.2
        with:
          # Service Account JSON key
          service_account: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          # GAE project name
          project_name: ${{ secrets.GCP_PROJECT_NAME }}
#      - name: Publish app to Google App Engine
#        uses: zxyle/publish-gae-action@v2.3.0
#        with:
#          # The service account email which will be used for authentication.
#          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
#          # The service account key which will be used for authentication.
#          service_account_key:  ${{ secrets.SERVICE_ACCOUNT_KEY }}
#          # GAE project id
#          project_id: ${{ secrets.GCP_PROJECT_NAME }}
#          # GAE variables to be written to the app.yaml file
#          gae_variables: ${{ secrets.SECRET_VARIABLES }}
#          # Path to the app.yml, Defaults to ./app.yml
#          gae_config_path: ./src/main/appengine/app.yaml

